CREATE TYPE "user_role" AS ENUM (
	'Admin',
	'User'
);

CREATE TYPE "report_status" AS ENUM (
	'Completed',
	'Rejected',
	'Pending',
	'In_Progress'
);

CREATE TABLE IF NOT EXISTS "Users" (
    "id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(100) NOT NULL UNIQUE,
    "password_hash" VARCHAR(255) NOT NULL,
    "role" USER_ROLE NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Sessions" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "token" VARCHAR(255) NOT NULL UNIQUE,
    "expires_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Reports" (
    "id" UUID NOT NULL,
    "version" BIGINT NOT NULL DEFAULT 0,
    "reporter_id" UUID NOT NULL,
    "category_id" UUID NOT NULL,
    "room_id" UUID NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "status" REPORT_STATUS NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "deleted_at" TIMESTAMP,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Buildings" (
    "id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "code" VARCHAR(255) NOT NULL UNIQUE,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Categories" (
    "id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Report_Image" (
    "id" UUID NOT NULL,
    "report_id" UUID NOT NULL,
    "image_url" VARCHAR(255) NOT NULL,
    "uploaded_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
    );

CREATE TABLE IF NOT EXISTS "Upvotes" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "report_id" UUID NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE UNIQUE INDEX "Upvotes_index_0"
    ON "Upvotes" ("user_id", "report_id");

CREATE TABLE IF NOT EXISTS "Rooms" (
    "id" UUID NOT NULL,
    "building_id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "floor" INTEGER NOT NULL,
    "code" VARCHAR(255) NOT NULL UNIQUE,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Report_Log" (
    "id" UUID NOT NULL,
    "admin_id" UUID NOT NULL,
    "report_id" UUID NOT NULL,
    "old_status" REPORT_STATUS NOT NULL,
    "new_status" REPORT_STATUS NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "User_Stats" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL UNIQUE,
    "report_count" INTEGER NOT NULL,
    "pending_report" INTEGER NOT NULL,
    "completed_report" INTEGER NOT NULL,
    "rejected_report" INTEGER NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Idempotency_Keys" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "key" VARCHAR(36) NOT NULL UNIQUE,
    "user_id" UUID NOT NULL,
    "request_path" VARCHAR(255) NOT NULL,
    "response_status" SMALLINT NOT NULL,
    "response_body" TEXT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "expires_at" TIMESTAMP NOT NULL,
    PRIMARY KEY("id")
);


CREATE INDEX "Idempotency_Keys_index_0"
    ON "Idempotency_Keys" ("user_id", "key");

ALTER TABLE "Report_Log"
    ADD FOREIGN KEY("admin_id") REFERENCES "Users"("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Report_Log"
    ADD FOREIGN KEY("report_id") REFERENCES "Reports"("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "Reports"
    ADD FOREIGN KEY("category_id") REFERENCES "Categories"("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Reports"
    ADD FOREIGN KEY("room_id") REFERENCES "Rooms"("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Reports"
    ADD FOREIGN KEY("reporter_id") REFERENCES "Users"("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Report_Image"
    ADD FOREIGN KEY("report_id") REFERENCES "Reports"("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "Rooms"
    ADD FOREIGN KEY("building_id") REFERENCES "Buildings"("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Upvotes"
    ADD FOREIGN KEY("report_id") REFERENCES "Reports"("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "Upvotes"
    ADD FOREIGN KEY("user_id") REFERENCES "Users"("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "Sessions"
    ADD FOREIGN KEY("user_id") REFERENCES "Users"("id") ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "User_Stats"
    ADD FOREIGN KEY("user_id") REFERENCES "Users"("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Idempotency_Keys"
    ADD FOREIGN KEY("user_id") REFERENCES "Users"("id") ON UPDATE NO ACTION ON DELETE CASCADE;